class NameAndPopulation {
    constructor(name, population){
        this.name=name;
        this.population=population;
    }
}

class RuleAndCapital {
    constructor(rule, capital) {
        this.rule = rule;
        this.capital = capital;
    }
}

let nameAndPopulation = [
    new NameAndPopulation("Chiny",1426129000),
    new NameAndPopulation("Indie",	1410266000),
    new NameAndPopulation("USA",	336023460),
    new NameAndPopulation("Indonezja",	280488501),	
    new NameAndPopulation("Pakistan",	228003290),	
    new NameAndPopulation("Brazylia",	218246900),	
    new NameAndPopulation("Nigeria",	216826390),	
    new NameAndPopulation("Bangladesz",	179740259),	
    new NameAndPopulation("Rosja",	147182123),
    new NameAndPopulation("Meksyk",	128649565),	
    new NameAndPopulation("Japonia",	124830000),	
    new NameAndPopulation("Etiopia"	,113656596),	
    new NameAndPopulation("Filipiny",	112479086),	
    new NameAndPopulation("DRK",	108407721),
    new NameAndPopulation("Egipt",	104390203),	
    new NameAndPopulation("Wietnam",	98510000),	
    new NameAndPopulation("Iranu",	87815354	),
    new NameAndPopulation("Turcja",	86154997),	
    new NameAndPopulation("Niemcy",	83349300),	
    new NameAndPopulation("Tajlandia",	69611069),	
    new NameAndPopulation("Francja",	68959599),	
    new NameAndPopulation("Zjednoczone Królestwo",	67647112),	
    new NameAndPopulation("Tanzania",	65890747),
    new NameAndPopulation("AfrykaPołudniowa",	61956900),
    new NameAndPopulation("Włochy",	59236213),
    new NameAndPopulation("Kenia",	57564296),
    new NameAndPopulation("Myanmar",	54045000),
    new NameAndPopulation("RepublikaKorei",	51780579),
    new NameAndPopulation("Kolumbia",	49258494),
    new NameAndPopulation("Uganda",	48006),
    new NameAndPopulation("Sudan",	47364750),
    new NameAndPopulation("Hiszpania",	46934632),
    new NameAndPopulation("Algieria",	45653000),
    new NameAndPopulation("Argentyna"	,44938712),
    new NameAndPopulation("Irak",	41310000),
    new NameAndPopulation("Ukraina",	40997699),
    new NameAndPopulation("Afganistan",	39225560),
    new NameAndPopulation("Kanada",	39163590),
    new NameAndPopulation("Polska",	38313035),
    new NameAndPopulation("Maroko",	37192950),
    new NameAndPopulation("Uzbekistan",	36110901),
    new NameAndPopulation("ArabiaSaudyjska",	35218169),
    new NameAndPopulation("Angola",	34825000),
    new NameAndPopulation("Malezja",	34511475),
    new NameAndPopulation("Wenezuela"	,33748000),
    new NameAndPopulation("Peru",	32162184),
    new NameAndPopulation("Ghana",	31418000),
    new NameAndPopulation("Mozambik",	31366000),
    new NameAndPopulation("Jemen",	31162000),
    new NameAndPopulation("Madagaskar",	28680342),
    new NameAndPopulation("Nepal",	28609000),
    new NameAndPopulation("WybrzeżeKościSłoniowej",	27717000),
    new NameAndPopulation("Australia",	26644000),
    new NameAndPopulation("Kamerun",	26348251),
    new NameAndPopulation("KoreaPółnocna",	25666000),
    new NameAndPopulation("Niger",	25314743),
    new NameAndPopulation("RepublikaChińska (Tajwan),",23782448),
    new NameAndPopulation("BurkinaFaso",	22870060),
    new NameAndPopulation("SriLanka",	21803000),
    new NameAndPopulation("Chile",	20723065),
    new NameAndPopulation("Mali",	20658000),
    new NameAndPopulation("Kazachstan",	19666840),
    new NameAndPopulation("Zambia",	19610769),
    new NameAndPopulation("Rumunia",	19401658),
    new NameAndPopulation("Senegal",	19256346),
    new NameAndPopulation("Malawi",	18563749),
    new NameAndPopulation("Ekwador",	18061650),
    new NameAndPopulation("Holandia",17734945),
    new NameAndPopulation("Gwatemala",	17679735),
    new NameAndPopulation("Zimbabwe",	17645000),
    new NameAndPopulation("Syria",	17070000),
    new NameAndPopulation("Czad",	15948000),
    new NameAndPopulation("Somalia",	15443000),
    new NameAndPopulation("Kambodża",	15288489),
    new NameAndPopulation("Gwinea",	12771000),
    new NameAndPopulation("Rwanda",	11952693),
    new NameAndPopulation("Tunezja",	11658341),
    new NameAndPopulation("Belgia",	11476279),
    new NameAndPopulation("Boliwia",	11469896),
    new NameAndPopulation("Kuba",	11333000),
    new NameAndPopulation("Burundi",	11215578),
    new NameAndPopulation("Jordania",	11099055),
    new NameAndPopulation("PołudniowySudan",	11062000),
    new NameAndPopulation("Haiti",	10911819),
    new NameAndPopulation("Grecja",	10741165),
    new NameAndPopulation("RepublikaDominikany",	10739000),
    new NameAndPopulation("Czech",	10693939),
    new NameAndPopulation("Portugalia",	10347892),
    new NameAndPopulation("Benin",	10315244),
    new NameAndPopulation("Szwecja",	10313447),
    new NameAndPopulation("Azerbejdżan",	10119100),
    new NameAndPopulation("ZEA",	9771000),
    new NameAndPopulation("Węgry",	9769526),
    new NameAndPopulation("Białoruś",	9255524),
    new NameAndPopulation("Honduras",	9158345),
    new NameAndPopulation("Izrael",	9136000),
    new NameAndPopulation("Tadżykistan",	9127000),
    new NameAndPopulation("Austria",	8915382),
    new NameAndPopulation("PapuaNowaGwinea",	8776000),
    new NameAndPopulation("Szwajcaria",	8570146),
    new NameAndPopulation("Iść",	8082000),
    new NameAndPopulation("SierraLeone",	7813000),
    new NameAndPopulation("Hongkong",	7524100),
    new NameAndPopulation("Paragwaj",	7152703),
    new NameAndPopulation("Laos",	7123205),
    new NameAndPopulation("Bułgaria",	6951482),
    new NameAndPopulation("Serbia",	6926705),
    new NameAndPopulation("Liban",	6856000),
    new NameAndPopulation("Libia",	6777000),
    new NameAndPopulation("Kirgistan",	6523500),
    new NameAndPopulation("Salvador",6454000),
    new NameAndPopulation("Nikaragua",	6198154),
    new NameAndPopulation("Turkmenia",	5942000),
    new NameAndPopulation("Dania",	5762082),
    new NameAndPopulation("Singapur",	5703600),
    new NameAndPopulation("Norwegia",5675900),
    new NameAndPopulation("Finlandia",5526774),
    new NameAndPopulation("Słowacja",	5449176),
    new NameAndPopulation("Norwegia",	5408000),
    new NameAndPopulation("Nowa Zelandia",	5102500),
    new NameAndPopulation("Kostaryka",	4953199),
    new NameAndPopulation("Irlandia",	4921500),
    new NameAndPopulation("PaństwoPalestyna",4816503),
    new NameAndPopulation("Kuwejt",	4207000),
    new NameAndPopulation("Oman",	4088690),
    new NameAndPopulation("Chorwacja",	4076246),
    new NameAndPopulation("Panama",	3764166),
    new NameAndPopulation("Gruzja",	3723500),
    new NameAndPopulation("Mołdawia",	3546500),
    new NameAndPopulation("Bośnia i Hercegowina",	3511372),
    new NameAndPopulation("Mongolia",	3480534),
    new NameAndPopulation("Urugwaj",	3415866),
    new NameAndPopulation("Portoryko",	3411307),
    new NameAndPopulation("Armenia",	2962100),
    new NameAndPopulation("Albania",	2845955),
    new NameAndPopulation("Litwa",	2790472),
    new NameAndPopulation("Katar",	2753045),
    new NameAndPopulation("Jamajka",	2726667),
    new NameAndPopulation("Słowenia",	2128240),
    new NameAndPopulation("Macedonia Północna",	2077132),
    new NameAndPopulation("Łotwa",	1908100),
    new NameAndPopulation("Republika Kosowa",	1907592),
    new NameAndPopulation("Bahrajn",	1451200),
    new NameAndPopulation("Estonia",	1328360),
    new NameAndPopulation("Cypr",875898),
    new NameAndPopulation("Czarnogóra",	622218),
    new NameAndPopulation("Luksemburg",	613894),
    new NameAndPopulation("SADR",582000),
    new NameAndPopulation("Surinam",	581000),
    new NameAndPopulation("Malta",	493559),
    new NameAndPopulation("Naddniestrze",467400),
    new NameAndPopulation("Islandia",	356991),
    new NameAndPopulation("NKR",	147000),
    new NameAndPopulation("Andora",76177),
    new NameAndPopulation("Grenlandia",	56196),
    new NameAndPopulation("Liechtenstein",	38378),
    new NameAndPopulation("Monako",	38300),
    new NameAndPopulation("San Marino",	34590),
    new NameAndPopulation("Watykan",	825),
    new NameAndPopulation("Fidżi", 890000)
];

let ruleAndCapital = [
    new RuleAndCapital("Xi Jinping", "Pekin"),
    new RuleAndCapital("Draupadi Murma", "Nowe Delhi"),
    new RuleAndCapital("Joe Biden", "Waszyngton"),
    new RuleAndCapital("Joko Widodo", "Djakarta"),
    new RuleAndCapital("Arif Alvi", "Islamabad"),
    new RuleAndCapital("Luis Inacio Lula da Silva", "Brazylia"),
    new RuleAndCapital("Mohammad Buhari", "Abudża"),
    new RuleAndCapital("Abdula Hamida", "Dhaka"),
    new RuleAndCapital("HUY", "Moskwa"),
    new RuleAndCapital("Andresa Manuela Lopeza Obradora", "Meksyk"),
    new RuleAndCapital("Fumio Kishida", "Tokio"),
    new RuleAndCapital("Sahle Work Zewde", "Addis Abeba"),
    new RuleAndCapital("Marco z bongbonga", "Manila"),
    new RuleAndCapital("Felix Tshisekedi", "Kinszasa"),
    new RuleAndCapital("Abdul-Fattah As-Sisi", "Kair"),
    new RuleAndCapital("Nguyen Xuan Phuc", "Hanoi"),
    new RuleAndCapital("Ibrahima Raisiego", "Teheran"),
    new RuleAndCapital("Recepa Tayyipa Erdogana", "Ankara"),
    new RuleAndCapital("Franka-Waltera Steinmeiera", "Berlin"),
    new RuleAndCapital("Prayut Chan-Ocha", "Bangkok"),
    new RuleAndCapital("Emmanuela Macrona", "Paryż"),
    new RuleAndCapital("Karol III", "Londyn"),
    new RuleAndCapital("Samia Hassan Suluhu", "Dodoma"),
    new RuleAndCapital("Cyryl Ramaphosa", "Pretoria"),
    new RuleAndCapital("Sergio Mattarella", "Rzym"),
    new RuleAndCapital("Williama Ruto", "Nairobi"),
    new RuleAndCapital("Myin Shwe", "Naypyidaw"),
    new RuleAndCapital("Yoon Seok Yeol", "Seul"),
    new RuleAndCapital("Gustavo Francisco Petro Urrego", "Bogota"),
    new RuleAndCapital("Yoweri Kaguta Museveni", "Kampali"),
    new RuleAndCapital("Abdel Fattah al-Burhan", "Chartum"),
    new RuleAndCapital("Filip VI", "Madryt"),
    new RuleAndCapital("Abdelmajid Tebbun", "Algieria"),
    new RuleAndCapital("Alberta Fernandeza", "Buenos Aires"),
    new RuleAndCapital("Abdul Latif Raszid", "Bagdad"),
    new RuleAndCapital("Władimir Żeleński", "Kijów"),
    new RuleAndCapital("Hassan Akhund", "Kabul"),
    new RuleAndCapital("Justin Trudeau", "Ottawa"),
    new RuleAndCapital("Andrzej Duda", "Warszawa"),
    new RuleAndCapital("Mahomet VI", "Rabat"),
    new RuleAndCapital("Szawkat Mirzijojew", "Taszkent"),
    new RuleAndCapital("Salmana bin Abdulaziza Al Sauda", "Rijad"),
    new RuleAndCapital("Juana Lourenço", "Luanda"),
    new RuleAndCapital("Anwara Ibrahima", "Kuala Lumpur"),
    new RuleAndCapital("Nicholas Maduro", "Carakas"),
    new RuleAndCapital("Dina Boluarte", "Lima"),
    new RuleAndCapital("Nana Akufo-Addo", "Akra"),
    new RuleAndCapital("Filipe Nyusi", "Maputo"),
    new RuleAndCapital("Riszad Mohammed al-Alimi", "Sana"),
    new RuleAndCapital("Andriej Razuelina", "Antananarywa"),
    new RuleAndCapital("Bidhya Devi Bhandari", "Katmandu"),
    new RuleAndCapital("Alassane Ouattara", "Jamusukro"),
    new RuleAndCapital("Antoniego Albaniza", "Canberra"),
    new RuleAndCapital("Paweł Bija", "Jaunde"),
    new RuleAndCapital("Kim Chen In", "Pjongjang"),
    new RuleAndCapital("Mohamed Bazum", "Niamey"),
    new RuleAndCapital("Tsai Ingwen", "Tajpej"),
    new RuleAndCapital("Ibrahim Traore", "Wagadugu"),
    new RuleAndCapital("Ranil Wickramasinghe", "Sri Jayewardenepura Kotte"),
    new RuleAndCapital("Czcionka Gabriela Borica", "Santiago"),
    new RuleAndCapital("Assimi Goita", "Bamako"),
    new RuleAndCapital("Kasym-Jomart Tokajew", "Astana"),
    new RuleAndCapital("Hakainde Hichilema", "Lusaka"),
    new RuleAndCapital("Klausa Johannisa", "Bukareszt"),
    new RuleAndCapital("Mak Sal", "Dakar"),
    new RuleAndCapital("Łazarz Czakwera", "Lilongwe"),
    new RuleAndCapital("Guillermo Lasso", "Quito"),
    new RuleAndCapital("Willem-Alexander", "Amsterdam"),
    new RuleAndCapital("Alejandro Giammattei", "Gwatemala"),
    new RuleAndCapital("Emmerson Mnangagwa", "Harare"),
    new RuleAndCapital("Baszar Assad", "Damaszek"),
    new RuleAndCapital("Mahamat Debi", "Ndżamena"),
    new RuleAndCapital("Hassan Szejk Mahmoud", "Mogadiszu"),
    new RuleAndCapital("Norodom Sihamoni", "Phnom Penh"),
    new RuleAndCapital("Mamady Dumbuya", "Konakri"),
    new RuleAndCapital("Paweł Kagame", "Kigali"),
    new RuleAndCapital("Qais powiedział", "Tunezja"),
    new RuleAndCapital("Philip", "Bruksela"),
    new RuleAndCapital("Ludwik Arce", "Sucre"),
    new RuleAndCapital("Miguela Diaz-Canela", "Hawana"),
    new RuleAndCapital("Evariste Ndayishimiye", "Gitega"),
    new RuleAndCapital("Abdullah II", "Amman"),
    new RuleAndCapital("Salvatore Kiir", "Dżuba"),
    new RuleAndCapital("Ariel Henri", "Port-au-Prince"),
    new RuleAndCapital("Katerina Sakellaropoulou", "Ateny"),
    new RuleAndCapital("Ludwika Abinadera", "Santo Domingo"),
    new RuleAndCapital("Miłosz Zeman", "Praga"),
    new RuleAndCapital("Marcelo Rebelo de Sousa", "Lizbona"),
    new RuleAndCapital("Patryk Talon", "Porto Novo"),
    new RuleAndCapital("Karol XVI Gustaw", "Sztokholm"),
    new RuleAndCapital("Ilham Alijew", "Baku"),
    new RuleAndCapital("Muhammad ibn Zayed Al Nahyan", "Abu Dabi"),
    new RuleAndCapital("Katalin Nowak", "Budapeszt"),
    new RuleAndCapital("HUY", "Mińsk"),
    new RuleAndCapital("Siomary Castro", "Tegucigalpa"),
    new RuleAndCapital("Książę Icchak", "Jerozolima"),
    new RuleAndCapital("Emomali Rachmon", "Duszanbe"),
    new RuleAndCapital("Aleksandra Van der Bellena", "Żyła"),
    new RuleAndCapital("Jamesa Marapę", "Port Moresby"),
    new RuleAndCapital("Alaina Berseta", "Berno"),
    new RuleAndCapital("Dla Essozimny Gnassingbe", "Lome"),
    new RuleAndCapital("Julius Maada Bio", "Wolne miasto"),
    new RuleAndCapital("Niema", "Niema"),
    new RuleAndCapital("Mario Abdo Beniteza", "Asuncion"),
    new RuleAndCapital("Thonglun Sisulit", "Wientian"),
    new RuleAndCapital("Rumen Radew", "Sofia"),
    new RuleAndCapital("Aleksander Vucic", "Belgrad"),
    new RuleAndCapital("Najib Mikati", "Bejrut"),
    new RuleAndCapital("Muhammad al-Manfi", "Trypolis"),
    new RuleAndCapital("Sadyr Japarow", "Biszkek"),
    new RuleAndCapital("Nayib Bukele", "San Salvador"),
    new RuleAndCapital("Daniel Ortega", "Managua"),
    new RuleAndCapital("Serdar Berdymuhamedow", "Aszchabad"),
    new RuleAndCapital("Małgorzata II", "Kopenhaga"),
    new RuleAndCapital("Halima Jakub", "Singapur"),
    new RuleAndCapital("Harald W", "Oslo"),
    new RuleAndCapital("Sauli Niinistö", "Helsinki"),
    new RuleAndCapital("Zuzana Czaputowa", "Bratysława"),
    new RuleAndCapital("Król Harald V", "Oslo"),
    new RuleAndCapital("Cindy Kiro", "Wellington"),
    new RuleAndCapital("Rodrigo Chaveza Roblesa", "San Jose"),
    new RuleAndCapital("Michaela Higginsa", "Dublin"),
    new RuleAndCapital("Mahmud Abbas", "Ramallah"),
    new RuleAndCapital("Nawaf al-Ahmed al-Jaber al-Sabah", "El Kuwejt"),
    new RuleAndCapital("Haytham ben Tarik", "Muskat"),
    new RuleAndCapital("Zoran Milanović", "Zagrzeb"),
    new RuleAndCapital("Laurentino Cortiso", "Panama"),
    new RuleAndCapital("Salome Zurabiszwili", "Tbilisi"),
    new RuleAndCapital("Maja Sandu", "Kiszyniów"),
    new RuleAndCapital("Christiana Schmidta", "Sarajewo"),
    new RuleAndCapital("Ukhnaagiin Khurelsukh", "Ułan Bator"),
    new RuleAndCapital("Luis Alberto Lacalle Pou", "Montevideo"),
    new RuleAndCapital("Pedro Pierluisi Urrutia", "San Juan"),
    new RuleAndCapital("Vahagn Chaczaturian", "Erewan"),
    new RuleAndCapital("Bayram Begai", "Tirana"),
    new RuleAndCapital("Gitanas Nauseda", "Wilno"),
    new RuleAndCapital("Tamim ibn Hamad Al Thani", "Dauha"),
    new RuleAndCapital("Patricka Allena", "Kingston"),
    new RuleAndCapital("Natasza Pirc-Musar", "Lublan"),
    new RuleAndCapital("Stewo Pendarowski", "Skopje"),
    new RuleAndCapital("Egils Levits", "Ryga"),
    new RuleAndCapital("Wiosa Osmani", "Prisztina"),
    new RuleAndCapital("Hamad ibn Isa Al Khalifa", "Manama"),
    new RuleAndCapital("Alar Karis", "Tallinn"),
    new RuleAndCapital("Nikos Anastasiades", "Południowa Nikozja"),
    new RuleAndCapital("Milo Djukanović", "Podgorica"),
    new RuleAndCapital("Henryk (Heinrich)", "Luksemburg"),
    new RuleAndCapital("Brahim Ghali", "Tifariti"),
    new RuleAndCapital("Chan Santohi", "Paramaribo"),
    new RuleAndCapital("Jerzy Vella", "Valletta"),
    new RuleAndCapital("Wadim Krasnosielski", "Tyraspol"),
    new RuleAndCapital("Gvyudni Johannesson", "Reykjavik"),
    new RuleAndCapital("Arayik Harutyunyan", "Stepanakert"),
    new RuleAndCapital("Javiera Espota Zamorę", "Andora la Vella"),
    new RuleAndCapital("Małgorzata II", "Niema"),
    new RuleAndCapital("Hansa Adama II", "Vaduz"),
    new RuleAndCapital("Albert II", "Monako"),
    new RuleAndCapital("Niema", "San Marino"),
    new RuleAndCapital("Fernando Verges Alzaga", "Watykan"),
    new RuleAndCapital("Williama Catonivere'a", "Suwa")
]

class Country {
    constructor(country, population, rule, capital) {
        this.country = country;
        this.population = population;
        this.rule = rule;
        this.capital = capital;       
    }
}

let table = [];
for (let i = 0; i < nameAndPopulation.length; i++) {
    table.push(
        new Country(nameAndPopulation[i].name, 
                    nameAndPopulation[i].population, 
                    ruleAndCapital[i].rule, 
                    ruleAndCapital[i].capital));
}

for (let i = 0; i < table.length; i++) {
    let row = table[i];
    console.log(`${row.country} ${row.population} ${row.rule} ${row.capital}`)
}